
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate


switch:
  - platform: rpi_pfio
    ports:
      0:
        name: Relay 3
      1:
        name: Relay 2
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
